[package]

name = "amqp"
version = "0.1.0"
authors = ["Andrii Dmytrenko <andrey@reevoo.com>"]
description = "AMQP/RabbitMQ protocol client"
repository = "https://github.com/Antti/rust-amqp"
license = "MIT/Apache-2.0"
keywords = ["amqp", "rabbitmq", "queue"]
readme = "Readme.md"
# build = "build.rs"

[lib]

name = "amqp"

[dependencies]
env_logger = "0.3"
log = "0.3"
url = "1.2"
amq-proto = "0.1.0"

[dev-dependencies]
# clippy  = "*"
